# Generated by Django 4.0.2 on 2022-02-27 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('product', '0002_favorite'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('client', 'product')},
        ),
    ]
