# Generated by Django 3.0 on 2019-12-14 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20191214_1804'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='client',
            table='client',
        ),
    ]
