# Generated by Django 3.0 on 2019-12-14 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_product_clients'),
        ('client', '0003_auto_20191214_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='products',
            field=models.ManyToManyField(blank=True, to='product.Product', verbose_name='Product'),
        ),
    ]
