# Generated by Django 3.0 on 2019-12-14 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_client_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='last_name',
        ),
        migrations.AddField(
            model_name='client',
            name='name',
            field=models.CharField(default=1, max_length=96, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
