# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# pre-commit run --all-files
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
# Python format
-   repo: https://github.com/psf/black
    rev: 21.8b0
    hooks:
    -   id: black
        exclude: ^venv/
        language: python
        language_version: python3
        args: [--skip-string-normalization]
# Import format
-   repo: https://github.com/timothycrosley/isort
    rev: 5.9.3
    hooks:
    -   id: isort
