services:
  django:
    image: "django_wishlist:1.0"
    container_name: django_wishlist
    build:
      context: ./
      dockerfile: ./.docker/django/Dockerfile
    volumes:
      - .:/home/django/wishlist
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: "curl -sS http://localhost:8000 || exit 1"
      timeout: 30s
      retries: 15
  # https://hub.docker.com/_/nginx
  nginx:
    image: nginx:1.21
    container_name: nginx_wishlist
    ports:
      - "80:80"
    environment:
      - NGINX_PORT=80
    volumes:
      - ./static:/var/www/static
      - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      django:
        condition: service_healthy
  # https://hub.docker.com/_/mysql
  mysql:
    image: mysql:8.0
    container_name: mysql_wishlist
    command: mysqld --default-authentication-plugin=mysql_native_password --skip-mysqlx
    environment:
      MYSQL_DATABASE: 'wishlist'
      MYSQL_USER: 'wishlist'
      MYSQL_PASSWORD: 'wishlist'
      MYSQL_ROOT_PASSWORD: 'wishlist'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: "mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD"
      timeout: 30s
      retries: 15
volumes:
  mysql-data:
