version: "3.9"
services:
  django:
    container_name: django_wishlist
    build:
      context: ./.docker/django
    volumes:
      - .:/home/ubuntu/wishlist
    depends_on:
      - mysql
    env_file:
      - .env
  # https://hub.docker.com/_/nginx
  nginx:
    container_name: nginx_wishlist
    image: nginx:1.19
    ports:
      - "80:80"
    environment:
      - NGINX_PORT=80
    volumes:
      - ./static:/var/www/static
      - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - django
  # https://hub.docker.com/_/mysql
  mysql:
    image: mysql:8.0
    container_name: mysql_wishlist
    command: mysqld --default-authentication-plugin=mysql_native_password --skip-mysqlx
    environment:
      MYSQL_DATABASE: 'wishlist'
      MYSQL_USER: 'wishlist'
      MYSQL_PASSWORD: 'wishlist'
      MYSQL_ROOT_PASSWORD: 'wishlist'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db:
