# Generated by Django 3.0 on 2019-12-14 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='clients',
            field=models.ManyToManyField(to='client.Client', verbose_name='Clients'),
        ),
        migrations.AlterField(
            model_name='product',
            name='review_score',
            field=models.SmallIntegerField(blank=True, choices=[(1, '★☆☆☆☆'), (2, '★★☆☆☆'), (3, '★★★☆☆'), (4, '★★★★☆'), (5, '★★★★★')], null=True, verbose_name='Review Score'),
        ),
    ]
