# Generated by Django 3.0 on 2019-12-14 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('product', '0002_auto_20191214_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='clients',
            field=models.ManyToManyField(blank=True, null=True, to='client.Client', verbose_name='Clients'),
        ),
    ]
