# Generated by Django 3.0 on 2019-12-14 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_product_clients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(db_index=True, max_length=96, verbose_name='Brand'),
        ),
    ]
