# Generated by Django 4.0.2 on 2022-02-27 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_rename_created_client_created_at_client_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True, verbose_name='Created at'
            ),
        ),
    ]
