name: Install Project

on:
  push:
    branches: [ master ]

jobs:
  building:
    name: Building
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        sudo apt-get install git build-essential python3-virtualenv libxml2-dev libxslt1-dev libevent-dev python3-dev libsasl2-dev libmysqlclient-dev libjpeg-dev libffi-dev libssl-dev -y
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: Create the Virtualenv
      run: |
        virtualenv .venv
    - name: Activate Virtualenv
      run: |
        source .venv/bin/activate
    - name: Install Python Dependencies
      run: |
        pip install -r requirements.txt
#    - name: Install Database
#      env:
#        SECRET_KEY: ${{ secrets.SECRET_KEY }}
#      run: |
#        ./manage.py migrate --settings=wishlist.settings_dev
    - name: Test the application
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}a
        ALLAN: ${{ env.ALLAN }}a
      run: |
        echo Olar
        echo $SECRET_KEY
        echo $ALLAN
        echo Xau
        pytest apps/
#    - name: Build and publish
#      env:
#        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
#        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
#      run: |
#        python setup.py sdist bdist_wheel
#        twine upload dist/*
