name: Build Docker

on:
  push:
    branches: [ master ]

jobs:
  building:
    name: Building
    runs-on: ubuntu-20.04
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: |
          echo $SECRET_KEY
